"""End-to-end invariant guards on the RENDERED page.

The unit tests prove each helper in isolation. These prove the thing that
actually protects Lilly: the HTML she receives. They run the real partition +
write_html and assert on the generated bytes, so a refactor that keeps a unit
test green but regresses the shipped page FAILS here. This is the safety net the
auto-merge / self-repair loop relies on — if any of these break, the fix does
not merge.

No network. No mocks of the rendering path.
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import find_admin_jobs as fa  # noqa: E402


def _full_row(**over):
    """A complete, normalized-shape row (every field write_html/_jobs_payload reads)."""
    row = {
        "id": None,
        "title": "Receptionist",
        "company": "UnityPoint Health",  # trusted -> local source stays 'safe'
        "location": "Des Moines, IA",
        "description": "",
        "source": "local",
        "hourly_min": 20.0,
        "hourly_max": 24.0,
        "verdict": "meets",
        "predicted": False,
        "created": "2026-06-01",
        "url": "https://example.com/job",
    }
    row.update(over)
    return row


def _build(rows, tmp_path):
    out = tmp_path / "index.html"
    safe = [r for r in rows if r["scam"]["level"] == "safe"]
    fa.write_html(safe, len(rows) - len(safe), len(rows), str(out), "2026-06-15 00:00")
    return out.read_text(encoding="utf-8")


def _embedded_jobs(html):
    """Pull the inline JOBS array back out of the built page."""
    m = re.search(r"const JOBS = (\[.*?\]);", html, re.DOTALL)
    assert m, "could not find embedded JOBS array in the page"
    return json.loads(m.group(1).replace("<\\/", "</"))


# ── Invariant: scams are HIDDEN, not labeled (must never reach the page) ──


def test_scam_row_never_reaches_rendered_page(tmp_path):
    safe = _full_row(title="Front Desk Receptionist", url="https://example.com/safe")
    scam = _full_row(
        title="EASY MONEY Data Entry",
        company="Mystery Co",
        source="remote",
        description="You must cash a check and wire transfer the balance to us.",
        url="https://example.com/scam",
    )
    rows = [safe, scam]
    for r in rows:
        r["scam"] = fa.scam_assessment(r, {})

    assert scam["scam"]["level"] != "safe", "fixture sanity: the scam must be caught"
    html = _build(rows, tmp_path)

    assert "Front Desk Receptionist" in html  # safe job is shown
    assert "EASY MONEY Data Entry" not in html  # scam title never shipped
    assert "wire transfer" not in html  # scam body never shipped
    titles = [j["title"] for j in _embedded_jobs(html)]
    assert titles == ["Front Desk Receptionist"]


def test_blocklisted_employer_never_reaches_page(tmp_path, monkeypatch):
    monkeypatch.setattr(fa, "BLOCKLIST", ["scamco"])
    row = _full_row(title="Admin Assistant", company="ScamCo LLC", url="https://example.com/b")
    row["scam"] = fa.scam_assessment(row, {})
    monkeypatch.setattr(fa, "BLOCKLIST", [])
    html = _build([row], tmp_path)
    assert "ScamCo" not in html
    assert _embedded_jobs(html) == []


# ── Invariant: a guessed/predicted wage is NEVER a number on the page ──


def test_predicted_wage_renders_no_number(tmp_path):
    row = _full_row(
        title="Office Assistant",
        hourly_min=22.0,
        hourly_max=26.0,
        predicted=True,
        verdict="unlisted",
        url="https://example.com/pred",
    )
    row["scam"] = {"level": "safe", "reasons": []}
    html = _build([row], tmp_path)

    job = _embedded_jobs(html)[0]
    assert job["pay"] == "Pay not listed"
    assert job["payNum"] == 0.0
    assert job["good"] is False
    # the predicted figures must not surface anywhere as this card's pay
    assert '"payNum": 22' not in html and '"payNum": 26' not in html


def test_employer_stated_wage_still_shows_number(tmp_path):
    # the other side of the invariant: a STATED wage is allowed to show.
    row = _full_row(hourly_min=20.0, hourly_max=24.0, predicted=False, verdict="meets")
    row["scam"] = {"level": "safe", "reasons": []}
    job = _embedded_jobs(_build([row], tmp_path))[0]
    assert "$20" in job["pay"] and job["good"] is True


# ── Invariant: XSS-safe rendering (no breakout from the embedded JSON) ──


def test_malicious_field_cannot_break_out_of_embedded_json(tmp_path):
    evil = "</script><img src=x onerror=alert(1)>"
    row = _full_row(title="Receptionist " + evil, url="https://example.com/x")
    row["scam"] = {"level": "safe", "reasons": []}
    html = _build([row], tmp_path)

    # the raw closing tag from the title must be neutralized; only the escaped
    # form may appear inside the embedded JSON.
    assert "</script><img" not in html
    assert "<\\/script>" in html
    # round-trips safely: the title is still present as data, just inert.
    assert _embedded_jobs(html)[0]["title"] == "Receptionist " + evil
